<?php
/**
 * Created by PhpStorm.
 * User: Денис
 * Date: 27.01.18
 * Time: 16:17
 */

$title = 'Delete city';
$this->headTitle($title);

$url   = $this->url('cities', ['action' => 'delete', 'id' => $id]);

?>

    <h1><?= $this->escapeHtml($title) ?></h1>

    <p>
        Are you sure that you want to delete
        "<?= $this->escapeHtml($city->name) ?>" by
    </p>

    <form action="<?= $url ?>" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="<?= (int) $city->id ?>" />
            <input type="submit" class="btn btn-danger" name="del" value="Yes" />
            <input type="submit" class="btn btn-success" name="del" value="No" />
        </div>
    </form>